FROM python:3.9.0-buster

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

WORKDIR /srv/startr

COPY requirements.txt .

RUN python3 -m pip install -r requirements.txt

ENV TFW_STARTER_WORKING_DIRECTORY=/tmp/workdir \
    TFW_STARTER_SOURCE_DIRECTORY=/srv/startr/avatao_startr/tfw

EXPOSE 5000

CMD ["python3", "startr.py"]